[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "calculator"
authors = [
    {name = "Firstname Lastname", email = "firstname.lastname@domain.x"},
]
description = "Extreme calculator"
version = '0.0.0'
